-- MySQL Script generated by MySQL Workbench
-- Fri Sep  4 20:50:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema app_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `app_db` ;

-- -----------------------------------------------------
-- Table `app_db`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NOT NULL,
  `rua` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `complemento` VARCHAR(150) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `app_db`.`passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`passengers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `facial` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `addresses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rg` (`rg` ASC) VISIBLE,
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  INDEX `fk_passengers_addresses1_idx` (`addresses_id` ASC) VISIBLE,
  CONSTRAINT `fk_passengers_addresses1`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `app_db`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `app_db`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plate` VARCHAR(10) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `capacity` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `plate` (`plate` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `app_db`.`access_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`access_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `passenger_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `action` ENUM('entry', 'exit') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `passenger_id` (`passenger_id` ASC) VISIBLE,
  INDEX `vehicle_id` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `access_events_ibfk_1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `app_db`.`passengers` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `access_events_ibfk_2`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `app_db`.`vehicles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `app_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'driver', 'responsible', 'supervisor') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `phone` VARCHAR(19) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `app_db`.`responsibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`responsibles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `addresses_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_responsible_addresses1_idx` (`addresses_id` ASC) VISIBLE,
  INDEX `fk_responsible_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_responsible_addresses1`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `app_db`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsible_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `app_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `app_db`.`passengers_responsibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`passengers_responsibles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `passengers_id` INT NOT NULL,
  `responsible_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passengers_has_responsible_responsible1_idx` (`responsible_id` ASC) VISIBLE,
  INDEX `fk_passengers_has_responsible_passengers1_idx` (`passengers_id` ASC) VISIBLE,
  CONSTRAINT `fk_passengers_has_responsible_passengers1`
    FOREIGN KEY (`passengers_id`)
    REFERENCES `app_db`.`passengers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passengers_has_responsible_responsible1`
    FOREIGN KEY (`responsible_id`)
    REFERENCES `app_db`.`responsibles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `app_db`.`cnh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`cnh` (
  `id_cnh` INT NOT NULL AUTO_INCREMENT,
  `numero_registro` VARCHAR(11) NOT NULL,
  `numero_espelho` VARCHAR(10) NOT NULL,
  `categoria` VARCHAR(5) NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_validade` DATE NOT NULL,
  `data_primeira_habilitacao` DATE NOT NULL,
  `uf_emissao` CHAR(2) NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `status_cnh` ENUM('Ativa', 'Suspensa', 'Cassada', 'Vencida') NULL DEFAULT 'Ativa',
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cnh`),
  UNIQUE INDEX (`numero_registro` ASC) VISIBLE,
  UNIQUE INDEX (`numero_espelho` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `app_db`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`drivers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `cnh_id_cnh` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_drivers_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_drivers_cnh1_idx` (`cnh_id_cnh` ASC) VISIBLE,
  CONSTRAINT `fk_drivers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `app_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_drivers_cnh1`
    FOREIGN KEY (`cnh_id_cnh`)
    REFERENCES `app_db`.`cnh` (`id_cnh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `shift` ENUM('morning', 'afternoon', 'evening') NOT NULL,
  `active` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`supervisors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`supervisors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_supervisors_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `app_db`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`route_stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`route_stops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `sequence` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_route_stop_sequence` (`route_id` ASC, `sequence` ASC) VISIBLE,
  INDEX `fk_route_stops_route` (`route_id` ASC) VISIBLE,
  INDEX `fk_route_stops_address` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_route_stops_route`
    FOREIGN KEY (`route_id`)
    REFERENCES `app_db`.`routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_route_stops_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `app_db`.`addresses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`route_passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`route_passengers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_id` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_route_passenger` (`route_id` ASC, `passenger_id` ASC) VISIBLE,
  INDEX `fk_route_passengers_route` (`route_id` ASC) VISIBLE,
  INDEX `fk_route_passengers_passenger` (`passenger_id` ASC) VISIBLE,
  CONSTRAINT `fk_route_passengers_route`
    FOREIGN KEY (`route_id`)
    REFERENCES `app_db`.`routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_route_passengers_passenger`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `app_db`.`passengers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`driver_vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`driver_vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `driver_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT TRUE,
  `assigned_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_driver_vehicle` (`driver_id` ASC, `vehicle_id` ASC) VISIBLE,
  INDEX `fk_driver_vehicles_driver` (`driver_id` ASC) VISIBLE,
  INDEX `fk_driver_vehicles_vehicle` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_driver_vehicles_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `app_db`.`drivers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_driver_vehicles_vehicle`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `app_db`.`vehicles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`trips` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `driver_id` INT NOT NULL,
  `supervisor_id` INT NULL DEFAULT NULL,
  `trip_date` DATE NOT NULL,
  `started_at` DATETIME NULL DEFAULT NULL,
  `finished_at` DATETIME NULL DEFAULT NULL,
  `status` ENUM('scheduled', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'scheduled',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_trips_date` (`trip_date` ASC) VISIBLE,
  INDEX `idx_trips_route_date` (`route_id` ASC, `trip_date` ASC) VISIBLE,
  INDEX `idx_trips_vehicle_date` (`vehicle_id` ASC, `trip_date` ASC) VISIBLE,
  INDEX `idx_trips_driver_date` (`driver_id` ASC, `trip_date` ASC) VISIBLE,
  INDEX `fk_trips_route` (`route_id` ASC) VISIBLE,
  INDEX `fk_trips_vehicle` (`vehicle_id` ASC) VISIBLE,
  INDEX `fk_trips_driver` (`driver_id` ASC) VISIBLE,
  INDEX `fk_trips_supervisor` (`supervisor_id` ASC) VISIBLE,
  CONSTRAINT `fk_trips_route`
    FOREIGN KEY (`route_id`)
    REFERENCES `app_db`.`routes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trips_vehicle`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `app_db`.`vehicles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trips_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `app_db`.`drivers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trips_supervisor`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `app_db`.`supervisors` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
